"""add chef_id to jobs

Revision ID: 82c4b9ac0826
Revises: 647b62e26dba
Create Date: 2026-09-01 10:25:30.561688
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c4b9ac0826'
down_revision: Union[str, Sequence[str], None] = '647b62e26dba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('chef_id', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('payment_frequency', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'jobs', ['chef_id'])
    op.create_foreign_key(None, 'jobs', 'users', ['chef_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='unique')
    op.drop_column('jobs', 'payment_frequency')
    op.drop_column('jobs', 'chef_id')
    # ### end Alembic commands ###