"""add is_active to workers

Revision ID: 9d69f5f741f1
Revises: af32b91f31fe
Create Date: 2026-09-11 19:33:39.757547
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d69f5f741f1'
down_revision: Union[str, Sequence[str], None] = 'af32b91f31fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('workers', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
    op.drop_column('workers', 'is_active')
    # ### end Alembic commands ###