"""add is_active to users

Revision ID: af32b91f31fe
Revises: 82c4b9ac0826
Create Date: 2026-09-10 13:14:09.896320
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "af32b91f31fe"
down_revision: str | Sequence[str] | None = "82c4b9ac0826"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "jobs",
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
    )

    op.add_column(
        "users",
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_active")
    op.drop_column("jobs", "is_active")
    # ### end Alembic commands ###
